import Foundation
import SwiftUI

// This file defines a set of sane default colors
// for the theming system, based on the default
// "Apple Blue" accent color.

public let default_light_primary = Color(0xFF007AFF)
public let default_light_onPrimary = Color(0xFFFFFFFF)
public let default_light_primaryContainer = Color(0xFFD8E2FF)
public let default_light_onPrimaryContainer = Color(0xFF001A41)
public let default_light_secondary = Color(0xFF565E71)
public let default_light_onSecondary = Color(0xFFFFFFFF)
public let default_light_secondaryContainer = Color(0xFFDBE2F9)
public let default_light_onSecondaryContainer = Color(0xFF141B2C)
public let default_light_tertiary = Color(0xFF715573)
public let default_light_onTertiary = Color(0xFFFFFFFF)
public let default_light_tertiaryContainer = Color(0xFFFBD7FC)
public let default_light_onTertiaryContainer = Color(0xFF29132D)
public let default_light_error = Color(0xFFBA1A1A)
public let default_light_errorContainer = Color(0xFFFFDAD6)
public let default_light_onError = Color(0xFFFFFFFF)
public let default_light_onErrorContainer = Color(0xFF410002)
public let default_light_background = Color(0xFFFEFBFF)
public let default_light_onBackground = Color(0xFF1B1B1F)
public let default_light_surface = Color(0xFFFEFBFF)
public let default_light_onSurface = Color(0xFF1B1B1F)
public let default_light_surfaceVariant = Color(0xFFE1E2EC)
public let default_light_onSurfaceVariant = Color(0xFF44474F)
public let default_light_outline = Color(0xFF74777F)
public let default_light_inverseOnSurface = Color(0xFFF2F0F4)
public let default_light_inverseSurface = Color(0xFF303033)
public let default_light_inversePrimary = Color(0xFFADC6FF)
public let default_light_shadow = Color(0xFF000000)
public let default_light_surfaceTint = Color(0xFF005BC1)
public let default_light_outlineVariant = Color(0xFFC4C6D0)
public let default_light_scrim = Color(0xFF000000)

public let default_dark_primary = Color(0xFF007AFF)
public let default_dark_onPrimary = Color(0xFF002E69)
public let default_dark_primaryContainer = Color(0xFF004493)
public let default_dark_onPrimaryContainer = Color(0xFFD8E2FF)
public let default_dark_secondary = Color(0xFFBFC6DC)
public let default_dark_onSecondary = Color(0xFF293041)
public let default_dark_secondaryContainer = Color(0xFF3F4759)
public let default_dark_onSecondaryContainer = Color(0xFFDBE2F9)
public let default_dark_tertiary = Color(0xFFDEBCDF)
public let default_dark_onTertiary = Color(0xFF402843)
public let default_dark_tertiaryContainer = Color(0xFF583E5B)
public let default_dark_onTertiaryContainer = Color(0xFFFBD7FC)
public let default_dark_error = Color(0xFFFFB4AB)
public let default_dark_errorContainer = Color(0xFF93000A)
public let default_dark_onError = Color(0xFF690005)
public let default_dark_onErrorContainer = Color(0xFFFFDAD6)
public let default_dark_background = Color(0xFF1B1B1F)
public let default_dark_onBackground = Color(0xFFE3E2E6)
public let default_dark_surface = Color(0xFF1B1B1F)
public let default_dark_onSurface = Color(0xFFE3E2E6)
public let default_dark_surfaceVariant = Color(0xFF44474F)
public let default_dark_onSurfaceVariant = Color(0xFFC4C6D0)
public let default_dark_outline = Color(0xFF8E9099)
public let default_dark_inverseOnSurface = Color(0xFF1B1B1F)
public let default_dark_inverseSurface = Color(0xFFE3E2E6)
public let default_dark_inversePrimary = Color(0xFF005BC1)
public let default_dark_shadow = Color(0xFF000000)
public let default_dark_surfaceTint = Color(0xFFADC6FF)
public let default_dark_outlineVariant = Color(0xFF44474F)
public let default_dark_scrim = Color(0xFF000000)
